Add explicit dependency to `mirage-crypto-rng`
The old version 0.10.6 fails with

```
File "src/ocamlorg_web/lib/ocamlorg_web.ml", line 12, characters 35-69:
12 |   Mirage_crypto_rng_lwt.initialize (module Mirage_crypto_rng.Fortuna);
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression is packed module, but the expected type is unit
```

So this adds the dependency to the build files as well as to the OPAM
files.