Forbid upgrade of mirage-kv-mem beyond 3.1.0 (#710)
Urgent kludge fix.

Allowing upgrade to 3.2.0 and beyond breaks the build. Here is
the error message:

opam exec -- dune build --root .
File "src/ocamlorg_web/lib/router.ml", lines 11-12, characters 6-54:
11 | ......let* store = store in
12 |       Asset.last_modified store (Mirage_kv.Key.v path).
Error: This expression has type (Ptime.t, Asset.error) result Lwt.t
       but an expression was expected of type (int * int64, 'a) result Lwt.t
       Type Ptime.t is not compatible with type int * int64
make: *** [Makefile:25: build] Error 1

Despite appearances, ptime does not seem to be the faulty dependency.
Preventing upgrade of prime beyond 1.0.0 does not solve the issue.

Co-authored-by: Cuihtlauac ALVARADO <cuihtmlauac@tarides.com>